
import { createClient } from '@supabase/supabase-js';

// --- CONFIGURATION ---
// 1. Go to https://supabase.com/ -> Create New Project (Recommend Pro Plan for OAC scale)
// 2. Go to Project Settings -> API
// 3. Replace the values below:

const SUPABASE_URL = 'YOUR_SUPABASE_PROJECT_URL';
const SUPABASE_ANON_KEY = 'YOUR_SUPABASE_ANON_KEY';

// Only initialize if keys are filled in
export const supabase = (SUPABASE_URL && SUPABASE_URL !== 'YOUR_SUPABASE_PROJECT_URL') 
    ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
    : null;

/**
 * ==========================================
 *   OAC ENTERPRISE SETUP GUIDE (SQL)
 * ==========================================
 * 
 * Copy and paste the following SQL into your Supabase "SQL Editor" 
 * to instantly set up your database structure.
 * 
 * ------------------------------------------
 
 -- 1. Create the Votes Table
 CREATE TABLE votes (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_name TEXT NOT NULL,
   user_email TEXT NOT NULL,
   vote_ids JSONB NOT NULL, -- Storing array of song IDs
   vote_reasons JSONB,      -- Storing reasons { "1": "Great beat" }
   created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
 );

 -- 2. Enable Row Level Security (Security Policy)
 ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

 -- 3. Policy: Allow anyone (anon) to INSERT votes
 CREATE POLICY "Allow public insert" ON votes FOR INSERT WITH CHECK (true);

 -- 4. Policy: Allow only admins to SELECT (read) votes
 -- Note: For simplicity in this app, we allow public read if you have the anon key,
 -- but in a strict enterprise app, you'd restrict this. 
 -- For now, let's allow read so the Leaderboard works for everyone if you want properly public results,
 -- or just for the Manager Dashboard.
 CREATE POLICY "Allow public read" ON votes FOR SELECT USING (true);

 * ------------------------------------------
 * 
 * STORAGE SETUP (For MP3s):
 * 1. Go to "Storage" in Supabase Dashboard.
 * 2. Create a new Bucket named "songs".
 * 3. Toggle "Public Bucket" to ON.
 * 4. Upload your audio files.
 * 5. The URL will be: https://[your-project-ref].supabase.co/storage/v1/object/public/songs/[filename].mp3
 * 
 * ==========================================
 */
